title: DSC Capstone Website
description: Characterizing Extrachromosomal DNA Regions with Graph Neural Networks
url: "https://vikwaran03.github.io/dsc-capstone-website/"

theme: minima

exclude:
  - README.md
  
authors:
  vikram:
    name: Vikram Venkatesh
    github: vikwaran03

  vrisan:
    name: Vrisan Dubey
    github: vdubey0

  matthew:
    name: Matthew Dalquist
    github: mdalquist

nav:
  - Home: /
  - Github: https://github.com/vikwaran03/DSC180B_Q2
  - Paper: https://drive.google.com/file/d/1RMm8bq_9rU4CFUQrDUupUsKiN2Jvkb8q/view?usp=drive_link
