title: DSC Capstone Website
description: Identifying ecDNA Genomic Regions using Graph Neural Networks
url: "https://vikwaran03.github.io/dsc-capstone-website/"

theme: minima

exclude:
  - README.md
  
authors:
  vikram:
    name: Vikram Venkatesh
    github: vikwaran03

  vrisan:
    name: Vrisan Dubey
    github: vdubey0

  matthew:
    name: Matthew Dalquist
    github: mdalquist
